server:
  port: 8080
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s

keycloak:
  realm: demo
  resource:
  auth-server-url:
  ssl-required:
  use-resource-role-mappings: true

app:
  keycloak:
    login:
      url:
    grant-type:
    client-id:
    client-secret:


