server:
  port: { SERVER_PORT:8080 }
  shutdown: graceful

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false

  liquibase:
    changeLog: classpath:/liquibase/db.changelog-master.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
#    drop-first: true

  datasource:
    url: jdbc:postgresql://localhost:5432/task-constructor
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    show-sql: true

